spring:
  datasource: url:jdbc:h2:tcp://localhost/~/my-db-test
  username: sa
  password:
  driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level:
  org.springframework: debug
  org.springframework.web: debug
